### PR TITLE
Add config for Agirbalyse matching

### PR DESCRIPTION
**Pull request by cmutel**

### CODE REVIEW

**Comment by fjuniorr** [comment]
@cmutel we can simply use the same field mapping config but point to `data/agribalyse-3.1.1-biosphere.json`

```bash
python main.py map data/agribalyse-3.1.1-biosphere.json \
                   data/ElementaryExchanges-3.7.json \
                   config/simapro-flows-ElementaryExchanges-3.7.toml
```

which yields (for https://github.com/fjuniorr/flowmapper/commit/3393ac21889c7fc7131a9c3b6188d0ab778e4dae):

```
100%|██████████████████████████████████████████████████████████████████| 5667/5667 [01:22<00:00, 68.30it/s]
5667 unique source flows...
4329 unique target flows...
3295 mappings of 3262 unique source flows (57.56% of total).
```

**Comment by fjuniorr** [comment]
I've [cherry picked](https://github.com/fjuniorr/flowmapper-ci/commit/08c55dceffc7f48941a34cde6eba1817e3a66e36) the more complete `.gitconfig` and otherwise I think we are good to close this. Sounds good @cmutel ?

**Comment by cmutel** [comment]
The difference between the configs is small - just `cas = ["CAS", "@casNumber"]` versus `cas = ["", "@casNumber"]`. 

I know we can use the existing config and it will work (it looks for the `CAS` column, which doesn't exist, so never returns a match, but it feels a bit weird to me to purposefully choose a config which is looking for a column we know isn't there... But ok, it works for now. At some point I assume we will want to add different config files for common use cases and we can revisit this.

**Comment by fjuniorr** [comment]
I agree that this can cause confusion. I was very focused on the fact that 

```json
  {
    "name": "1-Propanol, i-3,3,3-trifluoro-2,2-bis(trifluoromethyl)-, i-HFE-7100",
    "categories": [
      "Air",
      "(unspecified)"
    ],
    "unit": "kg",
    "CAS": ""
  }
```

or

```json
  {
    "name": "1-Propanol, i-3,3,3-trifluoro-2,2-bis(trifluoromethyl)-, i-HFE-7100",
    "categories": [
      "Air",
      "(unspecified)"
    ],
    "unit": "kg",
  }
```

in a given flowlist should be [handled](https://github.com/fjuniorr/flowmapper/pull/11/commits/1ba1e07b646733ecabe2340129c7493839dc0e25) in the same way.

> But ok, it works for now. At some point I assume we will want to add different config files for common use cases and we can revisit this.

👍

**Pull request closed without merging**
